"""Add full_name to user

Revision ID: 886cf80e8a93
Revises: 13f716720172
Create Date: 2018-12-06 12:48:58.329441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886cf80e8a93'
down_revision = '13f716720172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_user_full_name'), 'user', ['full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_full_name'), table_name='user')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
